### ISSUE TITLE
Help I don ´t know what to do any more

### ISSUE THREAD

**Issue by assqer** [LatvianModder/Item-Filters#37]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2023-05-01 05:20:07
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:58) ~[forge-1.19.4-45.0.50-universal.jar%23175!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:165) ~[forge-1.19.4-45.0.50-universal.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:591) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:582) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:585) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:196) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1363) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1160) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:731) ~[client-1.19.4-20230314.122934-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.0.50.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.50.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.latvian.mods.itemfilters.ItemFilters.setup(ItemFilters.java:33) ~[item-filters-forge-1902.2.9-build.46.jar%23166!/:1902.2.9-build.46] {re:classloading}
-- MOD itemfilters --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.50.jar%23172!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.50.jar%23171!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /home/agus_osx/.minecraft/mods/item-filters-forge-1902.2.9-build.46.jar
	Failure message: Item Filters (itemfilters) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1902.2.9-build.46
	Mod Issue URL: https://github.com/LatvianModder/Item-Filters/issues
	Exception message: java.lang.NoSuchMethodError: 'net.minecraft.world.item.CreativeModeTab dev.architectury.registry.CreativeTabRegistry.create(net.minecraft.resources.ResourceLocation, java.util.function.Supplier)'
Stacktrace:
	at dev.latvian.mods.itemfilters.ItemFilters.setup(ItemFilters.java:33) ~[item-filters-forge-1902.2.9-build.46.jar%23166!/:1902.2.9-build.46] {re:classloading}
	at dev.latvian.mods.itemfilters.forge.ItemFiltersForge.<init>(ItemFiltersForge.java:16) ~[item-filters-forge-1902.2.9-build.46.jar%23166!/:1902.2.9-build.46] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.50.jar%23172!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.50.jar%23171!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (amd64) version 6.2.0-20-generic
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 367028288 bytes (350 MiB) / 939524096 bytes (896 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Athlon 3000G with Radeon Vega Graphics
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4965.11
	Virtual memory used (MB): 4575.30
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 84.00
	JVM Flags: 7 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4096m
	OptiFine Version: OptiFine_1.19.4_HD_U_I4
	OptiFine Build: 20230408-043701
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6 (Core Profile) Mesa 23.0.2
	OpenGlRenderer: AMD Radeon Vega 3 Graphics (raven2, LLVM 15.0.7, DRM 3.49, 6.2.0-20-generic)
	OpenGlVendor: AMD
	CpuCount: 4
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.0.50.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.50.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.0.50.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.0.50.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.50.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		EnchantmentDescriptions-Forge-1.19.4-15.0.1.jar   |EnchantmentDescriptions       |enchdesc                      |15.0.1              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		moonlight-1.19.4-2.3.8-forge.jar                  |Moonlight Library             |moonlight                     |1.19.4-2.3.8        |COMMON_SET|Manifest: NOSIGNATURE
		FlowerPatch-forge-1.19.4-2.2.0.jar                |Flower Patch                  |flowerpatch                   |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.4-18.0.2.jar                 |Bookshelf                     |bookshelf                     |18.0.2              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		architectury-8.1.79-forge.jar                     |Architectury                  |architectury                  |8.1.79              |COMMON_SET|Manifest: NOSIGNATURE
		item-filters-forge-1902.2.9-build.46.jar          |Item Filters                  |itemfilters                   |1902.2.9-build.46   |ERROR     |Manifest: NOSIGNATURE
		jei-1.19.4-forge-13.1.0.7.jar                     |Just Enough Items             |jei                           |13.1.0.7            |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.4-45.0.50-universal.jar                |Forge                         |forge                         |45.0.50             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19.4-2.4.3.jar                |AppleSkin                     |appleskin                     |2.4.3+mc1.19.4      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.3-78.jar                           |Patchouli                     |patchouli                     |1.19.3-78           |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.19.4-10.0.0.2.jar                  |Clumps                        |clumps                        |10.0.0.2            |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |COMMON_SET|Manifest: NOSIGNATURE
		BetterAdvancements-1.19.2-0.2.2.147.jar           |Better Advancements           |betteradvancements            |0.2.2.147           |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 7545e205-eff3-4e10-9384-22817dae41e8
	FML: 45.0
	Forge: net.minecraftforge:45.0.50

**Comment by MaxNeedsSnacks** [comment]
1.19.2 builds of mods are generally not compatible with 1.19.4
